import { expect, test } from "@playwright/test";
import { writeQuestionCommandExtension } from "@agent-deck/testkit";
import { startHarness, type E2eHarness } from "../helpers/env.ts";

/**
 * Slice-11 gates: session titles appear in the chat list (generated by an
 * isolated pi helper), an ended session resumes with its transcript rebuilt
 * from pi's canonical session file, and a REAL extension_ui_request from pi
 * renders as a question card whose answer flows back.
 */

let harness: E2eHarness;

test.beforeAll(async () => {
  harness = await startHarness({
    chunkDelayMs: 20,
    extraExtensions: [writeQuestionCommandExtension()],
  });
});

test.afterAll(async () => {
  await harness.close();
});

test("a chat gets a generated title in the sidebar", async ({ page }) => {
  await page.goto(harness.baseUrl);
  await expect(page.getByTestId("status-indicator")).toHaveAttribute("data-status", "idle");

  await page.getByTestId("composer-input").fill("plan my birthday party");
  await page.getByTestId("send-button").click();
  await expect(page.getByTestId("assistant-text")).toContainText("birthday", { timeout: 30_000 });

  // Title arrives via the session_meta push once the helper finishes — the
  // "Draft · …" placeholder is replaced by a real generated title.
  await expect
    .poll(async () => (await page.getByTestId("chat-title").first().textContent()) ?? "", {
      timeout: 30_000,
    })
    .not.toMatch(/^Draft ·/);
});

test("an ended session resumes with its transcript rebuilt from pi's history", async ({ page }) => {
  await page.goto(harness.baseUrl);
  await expect(page.getByTestId("status-indicator")).toHaveAttribute("data-status", "idle");

  await page.getByTestId("composer-input").fill("remember the number 42");
  await page.getByTestId("send-button").click();
  await expect(page.getByTestId("assistant-text").last()).toContainText("42", {
    timeout: 30_000,
  });

  // Kill the pi subprocess server-side (as a crash/restart would).
  const sessionId = (await (await fetch(`${harness.baseUrl}/sessions`)).json()) as {
    sessions: Array<{ id: string; endedAt?: string; piSessionFile?: string }>;
  };
  const liveSession = harness.server.sessions.get(
    sessionId.sessions.filter((s) => !s.endedAt).at(-1)!.id,
  )!;
  // The resume handle must have been captured before we stop it.
  await expect.poll(() => liveSession.meta.piSessionFile !== undefined).toBe(true);
  await liveSession.stop();

  // Both panel layers stay mounted (native two-layer animation), so scope to
  // the collapsed list. Clicking an ended session resumes and rebuilds it.
  const chatButton = page.getByTestId("chat-list").getByTestId(`chat-${liveSession.meta.id}`);
  await expect(chatButton).toBeVisible();
  await chatButton.click();
  await expect(page.getByTestId("user-cell").last()).toContainText("remember the number 42", {
    timeout: 30_000,
  });
  await expect(page.getByTestId("assistant-text").last()).toContainText("42");

  // And the resumed session is live again: a follow-up streams.
  await page.getByTestId("composer-input").fill("still there?");
  await page.getByTestId("send-button").click();
  await expect(page.getByTestId("assistant-text").last()).toContainText("still there?", {
    timeout: 30_000,
  });
});

test("the app serves the brand SVG favicon (native app-icon parity)", async ({ page }) => {
  await page.goto(harness.baseUrl);

  // The document head links the brand SVG favicon (was previously absent —
  // the browser tab fell back to a blank icon).
  const icon = page.locator('link[rel="icon"]');
  await expect(icon).toHaveAttribute("type", "image/svg+xml");
  await expect(icon).toHaveAttribute("href", "/favicon.svg");

  // And the asset is actually served (bundled into the web root).
  const res = await page.request.get(`${harness.baseUrl}/favicon.svg`);
  expect(res.status()).toBe(200);
  expect(res.headers()["content-type"]).toContain("svg");
  expect(await res.text()).toContain("<svg");
});

test("a real extension_ui_request renders as a question card and the answer flows back", async ({
  page,
}) => {
  await page.goto(harness.baseUrl);
  await expect(page.getByTestId("status-indicator")).toHaveAttribute("data-status", "idle");

  await page.getByTestId("composer-input").fill("/ask-test");
  await page.getByTestId("send-button").click();

  const card = page.getByTestId("question-cell");
  await expect(card).toBeVisible({ timeout: 30_000 });
  await expect(card).toContainText("Test question");
  await expect(card).toContainText("Proceed with the mission?");

  await page.getByTestId("question-confirm-yes").click();
  await expect(card).toHaveAttribute("data-answered", "true");
});
